# Generated by Django 5.2.9 on 2026-02-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilefreelance',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='profilefreelance',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='competence', to='accounts.skills'),
        ),
    ]
