# Generated by Django 5.2.9 on 2026-03-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('disputed', 'Disputed')], default='active', max_length=20),
        ),
    ]
